### ISSUE TITLE
functionality to extract reads at NNN gaps in scaffolds?

### ISSUE THREAD

**Issue by juntkym** [Adamtaranto/teloclip#7]
Hi, @Adamtaranto , very nice tool!

Is it possible to add a new functionality that extracts reads soft-clipped at NNN gaps in scaffolds? This may be useful to reconstruct centromeric sequences.

Best regards,
Jun

**Comment by Adamtaranto** [comment]
Hi Jun, 

If you are trying to fill internal assembly gaps I think you could achieve this with some existing tools.

For example, you might filter your aligned reads for unique alignments only with samtools then use [samclip](https://github.com/tseemann/samclip) to extract soft-clipped alignments, and finally retain any of these alignments that occur within x bases of an NNN gap. This would require some manual gap-filling.

There are other tools which automate the gap-filling process: PBjelly works with aligned long reads, or the [Sealer](https://github.com/bcgsc/abyss/tree/master/Sealer) package from abyss.

**Comment by juntkym** [comment]
Thank you very much for your suggestions! I’ll give it a try.
